name: node-texas-senators-test
services:
- name: web
  build_command: npm i
  run_command: node main.js
  github:
    repo: matt-cale-do/node-texas-senators
    branch: main
  envs:
  - key: PHRASE
    value: "Hello Dan"
functions:
- name: funcs
  github:
    branch: main
    repo: matt-cale-do/node-texas-senators
  source_dir: adder/
  routes:
  - path: /functions